kind: Deployment
apiVersion: apps/v1
metadata:
  name: bothub-nlp-nlu-worker-pt-br-staging
  namespace: bothub
  labels:
    k8s-app: bothub-nlp-nlu-worker-pt-br
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      bothub-nlp-wod: pt_br
      track: staging
      k8s-app: bothub-nlp-nlu-worker-pt-br
  template:
    metadata:
      labels:
        bothub-nlp-wod: pt_br
        track: staging
        k8s-app: bothub-nlp-nlu-worker-pt-br
        name: bothub-nlp-nlu-worker-pt-br
    spec:
      containers:
      - name: bothub-nlp-nlu-worker-pt-br
        image: "452158872079.dkr.ecr.eu-west-1.amazonaws.com/bothub-nlp-nlu-worker:pt_br"
        command:
          - "celery"
          - "worker"
          - "--autoscale"
          - "5,3"
          - "-O"
          - "fair"
          - "--workdir",
          - "bothub_nlp_nlu_worker",
          - "-A"
          - "celery_app"
          - "-c"
          - "1"
          - "-l"
          - "INFO"
          - "-E"
          - "-Q"
          - "pt_br"
        env:
            - name: BOTHUB_ENGINE_URL
              value: 'https://api.ilhasoft.dev'
            - name: BOTHUB_NLP_CELERY_BACKEND_URL
              value: 'redis://redis-master.redis.svc.cluster.local:6379/9'
            - name: BOTHUB_NLP_CELERY_BROKER_URL
              value: 'redis://redis-master.redis.svc.cluster.local:6379/9'
            - name: BOTHUB_NLP_NLU_AGROUP_LANGUAGE_QUEUE
              value: 'true'
            - name: ENVIRONMENT
              value: 'staging'
            - name: SUPPORTED_LANGUAGES
              value: 'en:en_core_web_lg|pt'
            - name: BOTHUB_NLP_LANGUAGE_QUEUE
              value: 'pt_br'
            - name: BOTHUB_NLP_SERVICE_WORKER
              value: 'true'
        resources:
          limits:
            cpu: '4.0'
            memory: '7680Mi'
          requests:
            cpu: '1.0'
            memory: '1024Mi'
      tolerations:
        - key: "bothubpod"
          operator: "Equal"
          value: "false"
          effect: "NoExecute"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodename
                    operator: In
                    values:
                      - bothub1
